# Generated by Django 6.0.5 on 2026-06-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('team1_score', models.IntegerField()),
                ('team2_score', models.IntegerField()),
                ('overs', models.FloatField()),
            ],
        ),
    ]
