# Generated by Django 6.0.5 on 2026-06-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='predicted_winner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
